### ISSUE TITLE
Change to testify.Require instead of testify.Assert where needed

### ISSUE THREAD

**Issue by junkert** [smithoss/gonymizer#10]
Don't need to change it but I assume you're checking for a `nil` error return. The testify libraries have a specific `NoError` function.

Also, can be changed later if you want to, I generally recommend use of `testify/require` rather than `testify/assert`. Exactly the same set of functions, you can `s/assert/require/`. The difference is `assert` functions will continue the test even if the assert fails. That can often result in a `nil` pointer issue that causes a panic and big stack trace, making the test output harder to read. The `require` methods will hard fail and the rest of the specific test won't run (other tests will still get run).

_Originally posted by @endophage in https://github.com/smithoss/gonymizer/pull/5_

**Comment by u5surf** [comment]
@junkert I tried only to replace `testify/require` from `testify/assert` simply...

**Comment by junkert** [comment]
I tired this too on a test recently and it looks like the way we are calling tests (calling them directly in main_test.go) will require a little work to exit on error.

**Comment by junkert** [comment]
@u5surf do you want to put up a PR and I'll merge this in?
