### ISSUE TITLE
pg_dump (PostgreSQL) 13.3 errors

### ISSUE THREAD

**Issue by danturn** [smithoss/gonymizer#101]
Hi! thanks for this extremely useful tool!

this works well for us in pre PSQL 12, but in that release it appears that the -oids option was removed

so now i get an error

```
time="2021-09-14 20:03:53.173" level=error msg="STDERR: pg_dump: unrecognized option '--oids'
```

when taking the dump

I'm aware you don't officially support that version, but was wondering if you had plans to, or if it might be possible for me to add support (I'm not 100% sure what the change means yet, but i could possibly investigate)

also apologies for opening the issue with the totally random title initially, i was typing in the wrong window :smile:

**Comment by junkert** [comment]
Hi Daniel, thank you for the report. I have not ran the application with PostgreSQL 13 yet, but I think it is possible to remove this flag. I'll take a look in to this as soon as I have some free time.

Thanks for the report!

**Comment by danturn** [comment]
Heya @junkert, I'm happy to take a look if that helps, but wondering what your preferred approach would be?

e.g.

- A flag for pg_dump 12
- A flag for pg_dump version
- A specific flag to disable --oids as an option
- Check the pg_dump version and try and work it out internally

(also is there a way to give a password for the DB when running the tests? i see you can set the username with POSTGRES_USER?)

**Comment by junkert** [comment]
@danturn I like the option of allowing the user to choose if they need `oids` to add a flag for it. Maybe we should do:
* A specific flag to disable --oids as an option (e.g. --no-oids)

But instead of reversing the flag as `--no-oids` we could default to not include OIDS and if someone wants to use them the user can supply the flag `--oids`.  Considering this flag was removed going forward on new PSQL versions I think we should default to not using OIDS and allow the user to supply them if they are using an older version of PSQL.

Thoughts? Thanks for the help!

**Comment by danturn** [comment]
Ok sounds good, 

I'm pondering splitting out the arg creation from generator.go (in CreateDumpFile) into a new file

e.g. ArgBuilder.CreateDumpFIleArgs 

because otherwise im not sure how to test the --oids flag is being appended cos i can only integration test with one pg_dump version...

so i did that, and had a function with this signature:

```
func CreateDumpArgs(
  conf PGConfig,
  dumpfilePath,
  schemaPrefix string,
  excludeTables,
  excludeDataTables,
  excludeCreateSchemas,
  schemas []string,
  oids bool,
) [] string {
```

which led me on to think that possibly we could do the args creation before calling CreateDumpFile in the generator, so that CreateDumpFile would just take a string [] of args?

(FYI, i have never written go before, so im not aware of conventions preferences! feel free to direct me in whatever way works!)

**Comment by danturn** [comment]
https://github.com/smithoss/gonymizer/pull/102

**Comment by danturn** [comment]
Resolved in the PR above!

**Comment by danturn** [comment]
Resolved in PR above
