### ISSUE TITLE
UUID relationship between tables not working

### ISSUE THREAD

**Issue by leonardoviveiros** [smithoss/gonymizer#108]
I have a dataset with three tables.

One main `items` table that uses id as `uuid` that are unique, and two tables with things like `item_comment` and `item_history` that references the id from the main `items` table.

The problem is that ALL ids from `items` table are `00000000-0000-0000-0000-000000000000` so I lost the reference to `item_comment` and `item_history` tables.

I've configured the relationship "parentColumn", "parentSchema" and "parentTable" on both the `item` table and also the `item_history` and `item_comment` tables.

How can I fix that?
Thanks.

**Comment by junkert** [comment]
@leonardoviveiros have a couple questions:
1. Which version of Gonymizer are you using?
2. Does this happen on version `v1.2.3` and `v2.0.0`?

**Comment by luizm** [comment]
Hey @junkert 

I have the same issue using the latest version of gonymizer.. I'm trying to figure out what it the problem, let me know if you have an idea how to debug it better.

**Comment by junkert** [comment]
Hi @luizm. Which version are you using? Is this on the master branch?

**Comment by luizm** [comment]
> Hi @luizm. Which version are you using? Is this on the master branch?

Yes.. using master

**Comment by junkert** [comment]
I'll try to find some time to look into this today

**Comment by junkert** [comment]
So sorry this has been broken, I'm surprised that testing was working during this failure :( I'll look into this as well.

I was finally able to get a dev setup working again. I've been able to point to the addition of some of the multithreaded implantations from quite a while ago. This was added in version 2 and main.

Now that I have my dev setup working I'll need to track this bug down. Hopefully a fix coming soon.

**Comment by luizm** [comment]
Amazing.. thank so much for quick reply.

**Comment by junkert** [comment]
@luizm I accidentally committed to Master when making the fix tonight. This looks to fix the issue. Can you let me know if you run into any problems?

https://github.com/smithoss/gonymizer/commit/6fb69566e83f042480e1965ae710beb24c66c53a

**Comment by luizm** [comment]
@junkert it worked. Thank you so much

IMO you can close this issue.

**Comment by junkert** [comment]
Woo! Great to hear. Thank you for bringing this up @luizm !

**Comment by junkert** [comment]
Oh, almost forgot I have also released this version as `v2.0.1` and have tagged it appropriately. I'll add something to the top of the Issues to let others know that 2.0.0 is broken with UUIDs.
