### ISSUE TITLE
Support processor parameters

### ISSUE THREAD

**Issue by olivertso** [smithoss/gonymizer#71]
Some functions in [fake](https://github.com/icrowley/fake) package accept arguments, e.g. [DigitsN](https://godoc.org/github.com/icrowley/fake#DigitsN). Does Gonymizer support passing parameters to processors? Seems like it doesn't, but I might be missing something. If not, do you have any plan on this?

**Comment by junkert** [comment]
The plan was to use the min and max values inside the map JSON file for mapping input data to the faker function. For example, if a faker function only requires one input value one could use either min, max, or both for the value they want to send to the processor function and then handle sending that value into the Faker library.

AFAIK this capability is already there. You just need to get the value from the Processor structure.

```
            "Processors": [
                {
                    "Name": "Identity",
                    "Max": 0,
                    "Min": 0,
                    "Variance": 0,
                    "Comment": ""
                }
            ]
        },
```
```
       {
            "Comment": "",
            "TableSchema": "public",
            "TableName": "customers",
            "ColumnName": "customerid",
            "DataType": "integer",
            "ParentSchema": "",
            "ParentTable": "",
            "ParentColumn": "",
            "OrdinalPosition": 1,
            "IsNullable": false,
            "Processors": [
                {
                    "Name": "Identity",
                    "Max": 0,
                    "Min": 0,
                    "Variance": 0,
                    "Comment": ""
                }
            ]
        },
```

**Comment by olivertso** [comment]
Will look into it, thanks!
