### ISSUE TITLE
Official publicly available docker images of tagged releases

### ISSUE THREAD

**Issue by teerakarna** [smithoss/gonymizer#73]
It would be nice to have the official successful builds of gonymizer tagged releases publicly available on Docker Hub and/or Quay.

When I last checked the latest build on your Docker Hub repo was 6 months ago.

**Comment by junkert** [comment]
Looks like this is already there, but may be broken.

https://github.com/smithoss/gonymizer/blob/master/.circleci/config.yml#L74-L86

**Comment by junkert** [comment]
https://circleci.com/gh/smithoss/gonymizer/392 looks like it deployed to dockerhub. Not sure why Docker hub is not showing "latest" as the correct version.

I would not trust Docker Hub to contain the latest image. I highly recommend you build your own images and manage them yourself using a Docker image repository, like Amazon ECR. Docker Hub is quite unreliable and has been hacked in the past so I tend not to trust/use it -> https://www.zdnet.com/article/docker-hub-hack-exposed-data-of-190000-users/

**Comment by junkert** [comment]
Docker images have moved to here: https://hub.docker.com/r/junkert/gonymizer
