### ISSUE TITLE
Include only specified columns in the anonymized dump

### ISSUE THREAD

**Issue by ahilmer** [smithoss/gonymizer#80]
Hello gonymizer team,

we are currently evaluating gonymizer for our use cases.

We want to archive the following (simplified) use case:
- Table T with columns A,B
- Specified map file with only columns A,B
- whenever a new column C with sensitive data is added to table T, C will not be included in the anonymized dump 

Our experiments showed that even tough the column C was not specified in the map file it was still included in the dump.

Is there a way for the desired behavior?

**Comment by junkert** [comment]
Hi @ahilmer,

Are you using an `inclusive` or `exclusive` configuration for your map file? 
More on that here -> https://github.com/smithoss/gonymizer/#inclusive-map-files

**Comment by ahilmer** [comment]
Hi @junkert ,

thanks for your response.

It was not very clear for us on how to configure either `inclusive` or `exclusive`.

From my undertanding:
`inclusive`: You specify in your map file all the columns. 
`exclusive`: You specify only those columns you want to anoymize. 

But what if the schema evolves and you use the same map file?

My local experiments showed that newly added columns were in the processed dump even tough they were not specified.  

Maybe I should ask the question in a different way:

Can `gonymizer` ignore columns which were not specified in the map file?

**Comment by junkert** [comment]
In this case I recommend you use the `inclusive` file which will cause the `process` step to fail if a column exists in a table, but not in the map file. To do this you will need to add some extra steps to your CI/CD process for schema changes. I recommend the mapfile be updated at the same time someone adds a new column to the database. This adds an extra step to your typical development process, but guarentees that you will not be missing any PHI column that sneaks in.

1. You will first want to run the `map` command again to create a **new** map file. DO NOT OVERWRITE YOUR **original** map file... create a new one.
2. Run `diff` between the **new** map file and the **original** map file.
3. Copy / paste any new columns from the **new** map file to the **original** map file.
4. Edit the **original** map file and add `processors` to the new columns
5. Check in your **original** to Git
6. Run the process step

**Comment by ahilmer** [comment]
So the `inclusive` method can help there.

It is not clear for me from the documentation on how and where to specify the `inclusive` method. 

Lets say we have the script from the example:

`
...
    "process":  {
        "dump-file":            "phi_dump.sql",
        "map-file":             "db_map.json",
        "generate-seed":        true,
        "processed-file":       "anonymized_dump.sql"
    },
...
`

Where is here place to specify the method?

**Comment by ndrsllwngr** [comment]
@junkert I appreciate your proposed solution, but how do you **enable the `inclusive` method** to let the process step fail if there are column mismatches (column exists in table, but not in the map file)? Because at the moment, the process step won't fail if the `db_map.json` file lacks some columns. I am unable to find the instructions in the documentation regarding toggling the `inclusive` method.

**Comment by junkert** [comment]
The above PR should fix this issue. Thank you everyone for pointing out that this was missing. I will push this as release version 1.2.3 once it is approved and committed.

**Comment by ndrsllwngr** [comment]
Thank you a lot @junkert, much appreciated. 🙏
