### ISSUE TITLE
Concurrent processor

### ISSUE THREAD

**Issue by emintham** [smithoss/gonymizer#85]
Hey,

First off, thanks for sharing this great tool! It's been really helpful to me for a recent assignment I was tasked to do.

I'm not sure if you're interested in unsolicited feature PRs but I have a working concurrent version of gonymizer [here](https://github.com/emintham/gonymizer). It's currently functional but still very rough around the edges and not ready to be reviewed/merged and I just wanted to see if you would be interested in getting it merged back upstream in future.

To give you a bit of background about these changes, I was looking into anonymizing customer database dumps and your tool came up ahead of the competition in terms of fit for our use-case. I added a couple more processors for our specific requirements and it performed well. However, in our testing of our own test data (1.2GB) we found that it took ~3.5hours to finish processing the data. We expect our customer's data to be at least 19GB and would thus take too long to process on the customer's machine. I then spent a weekend optimizing gonymizer to try to get that time down and managed to get it down to only 2 minutes for the same 1.2GB dump running with 2 workers. However, these changes are fairly substantial and I may not have time to clean up the code/write tests/etc. for it to be mergeable.

The key changes (if you want to adapt some of these changes piecemeal) are:
1. concurrent processing with goroutines (this is a large change and requires changing the data structures in the processors to be concurrency-safe)-- this dropped ~3.5hours -> 4 minutes
2. changing the list of maps to be a map of maps-- this is a much smaller change and dropped 4 minutes to 2 minutes, though I'm not sure how much this would speed it up on its own-- perhaps something you can try if you're interested.
3. regex processing the COPY line instead of slicing the line multiple times-- I tried this much earlier than everything else on a smaller dataset and it dropped the time a tiny bit consistently.

If you want to try it out on your own data, feel free to check out my fork. You need to add `max-workers: N` where N is the number of workers (I recommend at least 2) to the config yaml file and also "MaxLength" field to each of your ColumnMaps (unrelated to any of the changes above but unfortunately part of the commit because I didn't have enough time to split the changes up into different commits).

The remaining work:
- [x] Update tests
- [x] Write more tests
- [x] Update README with changes
- [x] Split off changes into separate branch from my fork

Cheers,
Emin

**Comment by junkert** [comment]
Hi Emin,

Thank you so much for reaching out. I feel the work you have done definitely adds to the project and I believe there is some outstanding tasks to do exactly what you have already added. I feel this feature may help with adoption of Gonymizer for large datasets.

Please let me know in how I can help to get your changes added into the mainline. This would be great for a version 2.0 release as well so others can stick with the single threaded version and then move forward to the latest 2.x version when they see fit.

Levi

**Comment by emintham** [comment]
Hey Levi,

Here's my suggestion: I will try to pull out just the concurrent part of the changes into a PR so that there's less to review/test. Then, you can help me test in a sharded environment to see if there are any bugs (I don't have a sharded database and am not familiar with any possible edge cases that may occur in such an environment). Then if that's all good, we can merge that?

Emin

**Comment by emintham** [comment]
Pull request opened [here](https://github.com/smithoss/gonymizer/pull/86)

**Comment by junkert** [comment]
Thanks @emintham, I have asked some of the other SmithRx folks to see if they can review the PR as well. I'm out of town but will check things over next week when I'm back.
