### ISSUE TITLE
Wrap pg_dump's ability to dump only a few tables

### ISSUE THREAD

**Issue by GuillaumeRossolini** [smithoss/gonymizer#88]
Hi,

Conversely to the ability to exclude tables from the dump, which gonymizer already wraps, `pg_dump` also has the ability to specify exactly which tables should be exported:
```
  -t, --table=TABLE            dump the named table(s) only
```

This would be nice at the prototyping phase with gonymizer: just focus on a few tables, don't wait too much on the network.

Cheers

**Comment by GuillaumeRossolini** [comment]
Workaround for users in the meantime:

1. use `--log-level=DEBUG` for a first run with `gonymizer dump`;
2. keep a record of the `pg_dump` command line with all the options, and feel free to stop the container;
3. update your script to use this `pg_dump` command instead of the usual `gonymizer dump`, and add the `--table` options as needed.

**Comment by junkert** [comment]
This can be done by using the same flags as pg_dump. You will need to "exclude" instead of "include:

```
--exclude-table=table
```

See: https://www.postgresql.org/docs/11/app-pgdump.html

**Comment by GuillaumeRossolini** [comment]
Ended up using a different solution.
