### ISSUE TITLE
AlphaNumericScrambler breaks escaped encoding input

### ISSUE THREAD

**Issue by korpiq-tractr** [smithoss/gonymizer#91]
I tried to join the slack channel as per https://github.com/smithoss/gonymizer/blob/master/CONTRIBUTING.md but failed due to not having an existing account nor invitation at smith-oss.slack.com :(

AlphaNumericScrambler uses scrambleString, which naively replaces ASCII letters and numbers. When input contains eg. newlines dumped with `pg_dump` as '\n', some of these will eventually turn into '\x', which, when read by `psql`, consumes a two-digit hexadecimal number and injects corresponding byte into input stream, which then either turns that into some fancy unicode character, or more likely stumbles upon an invalid bytecode sequence.

Suggestion for fix: retain backslash escape sequences as is. Replace '\x..' with known-good values only.

I can provide said fix. Would you like to provide insight into it?

It should be possible to reproduce this along the following lines:

1. Create a database with utf-8 encoding and a 'text' column.
2. Insert large text with newlines.
3. Create a dump like `pg_dump --if-exists --clean "$DATABASE_URL" > dump.sql`
4. Create a matching gonymizer config including AlphaNumericScrambler, eg.
```
        {
            "Comment": "email, name or other free text",
            "TableSchema": "public",
            "TableName": "redacted",
            "ColumnName": "redacted",
            "DataType": "text",
            "ParentSchema": "",
            "ParentTable": "",
            "ParentColumn": "",
            "OrdinalPosition": 12,
            "IsNullable": true,
            "Processors": [
                {
                    "Name": "AlphaNumericScrambler",
                    "Max": 0,
                    "Min": 0,
                    "Variance": 0,
                    "Comment": ""
                }
            ]
        },
```
5. Run gonymizer on the dump like this (BTW it'd be super neat to be able to stream a dump through gonymizer instead)
```
    gonymizer process --map-file "$THIS_DIR/gonymizer-map.json" \
        --dump-file "dump.sql" \
        --processed-file "pseudonymized.sql"
```
6. Try to restore the processed dump as a database: `psql -qd "dbname" -f "pseudonymized.sql"`; with luck (improving with number of backslash-escapes in dump) you'll get errors like this actual one:
```
psql:<stdin>:5618: ERROR:  invalid byte sequence for encoding "UTF8": 0x97
CONTEXT:  COPY redacted, line 2723: "731	2020-08-17 11:40:14.697455	2020-09-08 04:16:11.137209	2020-08-27 06:00:00+00	2020-08-27 11:00:00..."
```

**Comment by korpiq-tractr** [comment]
I made a pull request at https://github.com/smithoss/gonymizer/pull/92

I hope this is not too rushy. Sorry I couldn't make it into the Slack before coming up with the fix.

**Comment by junkert** [comment]
All good. Thanks for this addition @korpiq-tractr. This should now be available on the MASTER branch. We will add this to version 2.1 once we get a couple more bug fixes in.
